# --- Site basics ---
locale: "en-GB"
title: "Merilin Martinson / Economics PhD Candidate"
title_separator: "-"
name: "Merilin Martinson"
description: "mostly a labour economist, partly a data scientist"
url: "https://merilinmartinson.github.io"
baseurl: ""                                # empty for user sites
repository: "MerilinMartinson/MerilinMartinson.github.io"

# --- Theme ---
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: pastel-merilin      # your pastel skin

# --- Build behaviour ---
include:
  - _pages
  - files
exclude:
  - .asset-cache
  - .bundle
  - .sass-cache
  - node_modules
  - vendor
  - tmp
  - config
  - README
  - LICENSE
  - CHANGELOG
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# --- Plugins ---
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-paginate

# --- Author block (sidebar) ---
author:
  name: "Merilin Martinson"
  avatar: "profile.png"
  bio: "phd. applied microeconomist first, data scientist second."
  location: "Berlin"
  email: "merilin.martinson [at] gmail.com"
  github: "MerilinMartinson"
  linkedin: "merilin-martinson"
  researchgate: "Merilin-Martinson"

# --- Collections ---
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# --- Defaults ---
defaults:
  - scope: { path: "", type: posts }
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope: { path: "", type: pages }
    values:
      layout: single
      author_profile: true

  - scope: { path: "", type: teaching }
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

  - scope: { path: "", type: publications }
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

  - scope: { path: "", type: portfolio }
    values:
      layout: single
      author_profile: false
      share: false
      comment: false

  - scope: { path: "", type: talks }
    values:
      layout: talk
      author_profile: false
      share: false

# --- Markdown & Sass ---
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
sass:
  sass_dir: _sass
  style: compressed

# --- URLs & archives ---
permalink: /:categories/:title/
category_archive: { type: liquid, path: /categories/ }
tag_archive:       { type: liquid, path: /tags/ }

# --- Misc ---
timezone: Europe/Berlin
compress_html:
  clippings: all
  ignore: { envs: development }
